### ISSUE TITLE
Can't get basic example to work

### ISSUE THREAD

**Issue by brothatru** [jbhannah/amperize#117]
Hi, 

I installed the latest version of your package in a new project folder.

Created an index.js with the following content (based on your example in README.md)

```
const Amperize = require('amperize');

const html = '<img src="https://example.com/image.jpg" />';

try {
  const amperize = new Amperize();
  amperize.parse(html, function (error, result) {
      if (error) {
          // do something with error
          return new Error(err);
      }
      // do something with result
      console.log('amp html should be logged here...', result);
      return result;
  });
} catch (e) {
  console.log(e)
}
```

When I try to run via terminal with `node index.js`, it just returns the regular html string.

It's not converting to `<amp-img>` tag like it should.

Any ideas what could be happening?

Node v9.11.2
amperize: ^0.3.8
Mac OS

**Comment by jbhannah** [comment]
I'll update the readme to point to a valid image URL.
