### ISSUE TITLE
Request for release tag

### ISSUE THREAD

**Issue by AileenCGN** [jbhannah/amperize#62]
Hi @jbhannah,

as we ([Ghost](https://github.com/TryGhost/Ghost)) want to use Amperize to transform our HTML into valid AMP HTML (see [here](https://github.com/TryGhost/Ghost/tree/amp)), I kindly request to make a release tag and continue with release cycles, so it's easier to use Amperize as a dependency and keep it updated.

It's a great tool with a lot of potential and I would love to see it becoming _the_ AMP HTML transform lib on GitHub.

Cheers,

Aileen

**Comment by jbhannah** [comment]
Pushing v0.3.0 now! Thanks for the work you've put into this — I initially created it for my own site but haven't been using it, and it's nice to see it find use in other projects and to have a reason to get back to working on it.
