### ISSUE TITLE
One wrong image fails it all

### ISSUE THREAD

**Issue by AileenCGN** [jbhannah/amperize#98]
This is related to #97. When one image fails in the `image-size` library, the whole process is stoped because we return an error.

IMO we should swallow the returned error from `image-size` and add fake sizes to the `<amp-img>` tag to continue parsing the rest of the passed HTML.

**Comment by kirrg001** [comment]
This was fixed, wasn't it?

**Comment by AileenCGN** [comment]
Yes, this was fixed with 94ac029dc7f973774c9ae78366d88dc8c592a7ec
